### ISSUE TITLE
Indent is wrong for a very simple program.

### ISSUE THREAD

**Issue by davidbau** [droplet-editor/droplet#17]
Repros on pencilcode.net:

(1) Drag a for [1..3] loop into a new program.
(2) Add a nested [1..3] loop
(3) Add an "fd 100" block innnermost.
(4) switch to code.
(5) see: indenting is wrong.

**Comment by sehgalvibhor** [comment]
I tried the code as stated above, i have added the screenshots . But, it seems the indenting is correct. Am i missing something? Whats the issue here?



![image](https://cloud.githubusercontent.com/assets/10993808/6542825/26118386-c52c-11e4-9456-1e0bd3cfaf2c.png)
![image](https://cloud.githubusercontent.com/assets/10993808/6542829/2f42721c-c52c-11e4-9910-12e6d9037f51.png)
